# Generated by Django 5.2.4 on 2026-08-25 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Palabra clave o frase que activa esta respuesta (en minúsculas)', max_length=100, unique=True)),
                ('respuesta', models.TextField(help_text='Mensaje que enviará el bot automáticamente')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(help_text='Número de WhatsApp (ej. 54911...)', max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Estética Wagner', max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('horarios', models.TextField(blank=True, null=True)),
                ('mensaje_bienvenida_bot', models.TextField(blank=True, help_text='Mensaje por defecto que enviará el bot cuando no reconozca un comando. Dejar vacío para desactivar respuesta por defecto.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('servicio', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app2.client')),
            ],
        ),
    ]
