# Generated by Django 5.2.4 on 2026-08-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_botresponse_client_profileconfig_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileconfig',
            name='telefono_whatsapp',
            field=models.CharField(blank=True, help_text='Número para el botón flotante de la landing page (ej. 5491166380592)', max_length=20, null=True),
        ),
    ]
