# Generated by Django 5.2.4 on 2026-08-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_profileconfig_telefono_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('INICIO', 'Inicio'), ('ELIGIENDO_SERVICIO', 'Eligiendo Servicio'), ('ELIGIENDO_FECHA', 'Eligiendo Fecha'), ('ESPERANDO_PAGO', 'Esperando Pago')], default='INICIO', max_length=50)),
                ('datos_reserva', models.JSONField(blank=True, default=dict)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profileconfig',
            name='datos_pago_bot',
            field=models.TextField(blank=True, help_text='Instrucciones de pago o CBU que el bot enviará al cliente para confirmar el turno.', null=True),
        ),
    ]
