# Generated by Django 5.2.4 on 2026-08-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_botsession_service_profileconfig_datos_pago_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Un beneficio por línea', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 60 minutos', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
