# Generated by Django 5.2.4 on 2026-08-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_service_beneficios_service_duracion_service_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
